export const types = Object.freeze({

    // === PEOPLE ===

    // Sync
    FILMS_START_FETCHING: 'FILMS_START_FETCHING',
    FILMS_STOP_FETCHING: 'FILMS_STOP_FETCHING',
    FILMS_FILL: 'FILMS_FILL',
    FILMS_SET_FETCHING_ERROR: 'FILMS_SET_FETCHING_ERROR',

    // Async
    FILMS_FETCH_ASYNC: 'FILMS_FETCH_ASYNC',

    // === PERSON ===

    // Sync
    FILM_START_FETCHING: 'FILM_START_FETCHING',
    FILM_STOP_FETCHING: 'FILM_STOP_FETCHING',
    FILM_FILL: 'FILM_FILL',
    FILM_SET_FETCHING_ERROR: 'FILM_SET_FETCHING_ERROR',

    // Async
    FILM_FETCH_ASYNC: 'FILM_FETCH_ASYNC',
});
