export const types = Object.freeze({

    // === PEOPLE ===

    // Sync
    PEOPLE_START_FETCHING: 'PEOPLE_START_FETCHING',
    PEOPLE_STOP_FETCHING: 'PEOPLE_STOP_FETCHING',
    PEOPLE_FILL: 'PEOPLE_FILL',
    PEOPLE_SET_FETCHING_ERROR: 'PEOPLE_SET_FETCHING_ERROR',

    // Async
    PEOPLE_FETCH_ASYNC: 'PEOPLE_FETCH_ASYNC',

    // === PERSON ===

    // Sync
    PERSON_START_FETCHING: 'PERSON_START_FETCHING',
    PERSON_STOP_FETCHING: 'PERSON_STOP_FETCHING',
    PERSON_FILL: 'PERSON_FILL',
    PERSON_SET_FETCHING_ERROR: 'PERSON_SET_FETCHING_ERROR',

    // Async
    PERSON_FETCH_ASYNC: 'PERSON_FETCH_ASYNC',
});
